/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02;

import org.junit.jupiter.api.Test;
import org.w3c.dom.css.Rect;

import static org.junit.jupiter.api.Assertions.*;


import java.util.Arrays;

class RectangleTest {
    @Test
    void testHarnessWorking() {
        assertTrue(true);
    }

    @Test
    void createDefaultRect() {
        Rectangle r = new Rectangle();
        assertEquals(1, r.getWidth());
        assertEquals(1, r.getHeight());
        assertEquals(0, r.getX());
        assertEquals(0, r.getY());
    }

    @Test
    void customRectangle() {
        Rectangle r = new Rectangle(5, 5, 10, 10);
        assertEquals(5, r.getX());
        assertEquals(5, r.getY());
        assertEquals(10, r.getWidth());
        assertEquals(10, r.getHeight());
    }
    @Test
    void changeWidthValid() {
        Rectangle r = new Rectangle(5,5,10,10);
        r.setWidth(20);
        assertEquals(20,r.getWidth());
    }
    @Test
    void changeWidthNegative() {
        Rectangle r = new Rectangle(5,5,10,10);
        assertThrows(IllegalArgumentException.class, () -> {r.setWidth(-10);});
    }
    @Test
    void changeHeightValid() {
        Rectangle r = new Rectangle(0, 0, 5, 5);
        r.setHeight(10);
        assertEquals(10, r.getHeight());
    }
    @Test
    void changeHeightNegative() {
        Rectangle r = new Rectangle(0, 0, 5, 5);
        assertThrows(IllegalArgumentException.class, () -> r.setHeight(0));
    }
    @Test
    void changeXandV() {
        Rectangle r = new Rectangle();
        r.setX(10);
        r.setY(20);

        assertEquals(10, r.getX());
        assertEquals(20, r.getY());
    }
    @Test
    void areaRectangle() {
        Rectangle r = new Rectangle(0, 0, 4, 5);
        assertEquals(20, r.area());
    }
    @Test
    void rectanglesEqual() {
        Rectangle a = new Rectangle(1, 2, 3, 4);
        Rectangle b = new Rectangle(1, 2, 3, 4);

        assertEquals(a, b);
    }
    @Test
    void rectanglesNotEqual() {
        Rectangle r1 = new Rectangle(1, 2, 3, 4);
        Rectangle r2 = new Rectangle(1, 2, 3, 5);

        assertNotEquals(r1, r2);
    }
    @Test
    void rectangleContainsAnother() {
        Rectangle outer = new Rectangle(0, 0, 8, 12);
        Rectangle inner = new Rectangle(2, 2, 4, 4);

        assertTrue(outer.contains(inner));
    }
    @Test
    void rectangleDoesNotContain() {
        Rectangle outer = new Rectangle(0, 0, 3, 4);
        Rectangle other = new Rectangle(9, 9, 5, 7);
        assertFalse(outer.contains(other));
    }
}
