/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab04;

import org.apache.commons.math3.geometry.spherical.oned.ArcsSet;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.*;
import java.util.stream.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.*;
import org.junit.jupiter.params.provider.*;

class SplittingTest {

    @ParameterizedTest
    @MethodSource("generator")
    void canBalance(String description, int[] nums, boolean expected) {
        boolean result = Splitting.canBalance(nums);
        assertEquals(expected, result);
    }

    private static Stream<Arguments> generator() {
        return Stream.of(
                Arguments.of("null array",
                        null,
                        false),

                // length = 1 -> false
                Arguments.of("single element",
                        new int[]{5},
                        false),

                // odd sum -> false
                Arguments.of("odd sum",
                        new int[]{1, 2},
                        false),

                // can split into half
                Arguments.of("can balance",
                        new int[]{1, 1, 1, 2, 1},
                        true),

                // even sum but can't split
                Arguments.of("even sum but cannot balance",
                        new int[]{2, 1, 1, 2, 4},
                        false),

                // can be split from the first element
                Arguments.of("balance at first element",
                        new int[]{3, 1, 2},
                        true)
        );
    }
}