/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02;

import com.google.common.annotations.VisibleForTesting;

public class Rectangle {

    private int x;
    private int y;
    private int width;
    private int height;

    public Rectangle(){
        this(0,0,1,1);
    }

    public Rectangle(int x, int y, int width, int height) {
        this.x = x;
        this.y = y;
        this.width = width;
        this.height = height;
    }
    public int getX() {
        return x;
    }
    public int getY() {
        return y;
    }
    public int getWidth() {
        return width;
    }
    public int getHeight() {
        return height;
    }
    public void setWidth(int width) {
        if (width <= 0) {
            throw new IllegalArgumentException("Width must be a positive value");
        }
        this.width = width;
    }

    public void setHeight(int height) {
        if (height <= 0){
            throw new IllegalArgumentException("Height must be a positve value");
        }
        this.height = height;
    }

    public void setX(int x){
        this.x = x;
    }

    public void setY(int y){
        this.y = y;
    }

    public int area(){
        return width*height;
    }

    public boolean equals(Object o){
        if (this == o){
            return true;
        }
        if (!(o instanceof Rectangle)) return false;

        Rectangle other = (Rectangle) o;
        return x == other.x &&
                y == other.y &&
                width == other.width &&
                height == other.height;
    }
    public boolean contains(Rectangle other) {
        return other.x >= this.x &&
                other.y >= this.y &&
                other.x + other.width <= this.x + this.width &&
                other.y + other.height <= this.y + this.height;
    }
}
